# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/02e_pds.lroc_index.ipynb (unless otherwise specified).

__all__ = ['LROCIndex']

# Cell
import warnings
from nbverbose.showdoc import *

# Cell
class LROCIndex:
    def __init__(self):
        warnings.warn("LROCIndex not implemented yet.")