# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Config": "00_config.ipynb",
         "config": "00_config.ipynb",
         "logger": "02_pdstools.indexes.ipynb",
         "nasa_date_format": "01_utils.ipynb",
         "nasa_dt_format": "01_utils.ipynb",
         "nasa_dt_format_with_ms": "01_utils.ipynb",
         "standard_date_format": "01_utils.ipynb",
         "standard_dt_format": "01_utils.ipynb",
         "standard_dt_format_with_ms": "01_utils.ipynb",
         "nasa_date_to_iso": "01_utils.ipynb",
         "iso_to_nasa_date": "01_utils.ipynb",
         "nasa_datetime_to_iso": "01_utils.ipynb",
         "iso_to_nasa_datetime": "01_utils.ipynb",
         "replace_all_nasa_times": "01_utils.ipynb",
         "get_gdal_center_coords": "01_utils.ipynb",
         "ProgressBar": "01_utils.ipynb",
         "parse_http_date": "01_utils.ipynb",
         "get_remote_timestamp": "01_utils.ipynb",
         "download": "01_utils.ipynb",
         "url_retrieve": "01_utils.ipynb",
         "height_from_shadow": "01_utils.ipynb",
         "indices_root": "02_pdstools.indexes.ipynb",
         "Index": "02_pdstools.indexes.ipynb",
         "IndexDB": "02_pdstools.indexes.ipynb",
         "indexdb": "02_pdstools.indexes.ipynb",
         "list_available_index_files": "02_pdstools.indexes.ipynb",
         "replace_url_suffix": "02_pdstools.indexes.ipynb",
         "PVLColumn": "02_pdstools.indexes.ipynb",
         "IndexLabel": "02_pdstools.indexes.ipynb",
         "index_to_df": "02_pdstools.indexes.ipynb",
         "decode_line": "02_pdstools.indexes.ipynb",
         "find_mixed_type_cols": "02_pdstools.indexes.ipynb",
         "fix_hirise_edrcumindex": "02_pdstools.indexes.ipynb",
         "__all__": "03_isis.specialpixels.ipynb",
         "SPECIAL_PIXELS": "03_isis.specialpixels.ipynb"}

modules = ["config.py",
           "utils.py",
           "pdstools/indexes.py",
           "isis/specialpixels.py"]

doc_url = "https://michaelaye.github.io/planetarypy/"

git_url = "https://github.com/michaelaye/planetarypy/tree/{branch}/"

def custom_doc_links(name): return None
