# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Config": "00_config.ipynb",
         "config": "00_config.ipynb",
         "logger": "02a_pds.indexes.ipynb",
         "nasa_date_format": "01_utils.ipynb",
         "nasa_dt_format": "01_utils.ipynb",
         "nasa_dt_format_with_ms": "01_utils.ipynb",
         "standard_date_format": "01_utils.ipynb",
         "standard_dt_format": "01_utils.ipynb",
         "standard_dt_format_with_ms": "01_utils.ipynb",
         "nasa_date_to_iso": "01_utils.ipynb",
         "iso_to_nasa_date": "01_utils.ipynb",
         "nasa_datetime_to_iso": "01_utils.ipynb",
         "iso_to_nasa_datetime": "01_utils.ipynb",
         "replace_all_nasa_times": "01_utils.ipynb",
         "ProgressBar": "01_utils.ipynb",
         "parse_http_date": "01_utils.ipynb",
         "get_remote_timestamp": "01_utils.ipynb",
         "download": "01_utils.ipynb",
         "url_retrieve": "01_utils.ipynb",
         "height_from_shadow": "01_utils.ipynb",
         "get_gdal_center_coords": "01_utils.ipynb",
         "file_variations": "01_utils.ipynb",
         "storage_root": "04_hirise.ipynb",
         "dynamic_urls": "02a_pds.indexes.ipynb",
         "PVLColumn": "02a_pds.indexes.ipynb",
         "IndexLabel": "02a_pds.indexes.ipynb",
         "index_to_df": "02a_pds.indexes.ipynb",
         "Index": "02a_pds.indexes.ipynb",
         "decode_line": "02a_pds.indexes.ipynb",
         "find_mixed_type_cols": "02a_pds.indexes.ipynb",
         "fix_hirise_edrcumindex": "02a_pds.indexes.ipynb",
         "CTXIndex": "02b_pds.ctx_index.ipynb",
         "find_indexes": "02c_pds.apps.ipynb",
         "get_index": "02c_pds.apps.ipynb",
         "find_instruments": "02c_pds.apps.ipynb",
         "baseurl": "04_hirise.ipynb",
         "edrindex": "03_ctx.ipynb",
         "catch_isis_error": "03_ctx.ipynb",
         "CTXEDR": "03_ctx.ipynb",
         "CTXEDRCollection": "03_ctx.ipynb",
         "rdrindex": "04_hirise.ipynb",
         "RGB_NOMAP": "04_hirise.ipynb",
         "RGB_NOMAPCollection": "04_hirise.ipynb"}

modules = ["config.py",
           "utils.py",
           "pds/indexes.py",
           "pds/ctx_index.py",
           "pds/apps.py",
           "ctx.py",
           "hirise.py"]

doc_url = "https://michaelaye.github.io/nbplanetary/"

git_url = "https://github.com/michaelaye/nbplanetarypy/tree/{branch}/"

def custom_doc_links(name): return None
