# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Config": "00_config.ipynb",
         "config": "00_config.ipynb"}

modules = ["config.py"]

doc_url = "https://michaelaye.github.io/planetarypy/"

git_url = "https://github.com/michaelaye/planetarypy/tree/{branch}/"

def custom_doc_links(name): return None
