# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/07_diviner.ipynb.

# %% auto 0
__all__ = ['hostname', 'get_data_path']

# %% ../notebooks/07_diviner.ipynb 7
import socket
from pathlib import Path

import hvplot.xarray  # noqa
import pandas as pd
from .config import config
from .utils import url_retrieve
from yarl import URL

# %% ../notebooks/07_diviner.ipynb 8
hostname = socket.gethostname()
if hostname.startswith("luna") and hostname.endswith("diviner.ucla.edu"):
    storage_root = Path("/q/marks/feidata/DIV:opsL1A/data")
else:
    storage_root = config.storage_root / "missions/lro/diviner"

# %% ../notebooks/07_diviner.ipynb 21
def get_data_path(tstr):
    dm = DataManager(tstr)
    if not dm.local_path.exists():
        dm.download()
    return dm.local_path
