package:
  name: planetarypy
  version: 0.17.0
source:
  sha256: cc816533828276755465171ca08e738179c9be6b72b563da6541770157b049ad
  url: https://files.pythonhosted.org/packages/e7/67/c6b5af2782b74a34cad5b5efd278a8206c0f9853b4d94859132d4c9d595d/planetarypy-0.17.0.tar.gz
about:
  dev_url: https://michaelaye.github.io
  doc_url: https://michaelaye.github.io
  home: https://michaelaye.github.io
  license: Apache Software
  license_family: APACHE
  summary: Python Tools for Planetary Science
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - michaelaye
requirements:
  host:
  - pip
  - python
  - packaging
  - tomlkit
  - pandas
  - pvl
  - numpy
  - python-dateutil
  - tqdm
  - lxml
  - yarl
  - hirise-tools
  - kalasiris
  - dask
  - fastparquet
  run:
  - pip
  - python
  - packaging
  - tomlkit
  - pandas
  - pvl
  - numpy
  - python-dateutil
  - tqdm
  - lxml
  - yarl
  - hirise-tools
  - kalasiris
  - dask
  - fastparquet
test:
  imports:
  - planetarypy
