package:
  name: planetarypy
  version: 0.17.1
source:
  sha256: f0b7b7b48606d17e2be5c396d68a71f6c8c856120824b3d944b62fedde143aac
  url: https://files.pythonhosted.org/packages/1b/09/e4f2f27a883aac71a22b6d497a29670d8942dcb2c3b9367d119fc38c6680/planetarypy-0.17.1.tar.gz
about:
  dev_url: https://michaelaye.github.io
  doc_url: https://michaelaye.github.io
  home: https://michaelaye.github.io
  license: Apache Software
  license_family: APACHE
  summary: Python Tools for Planetary Science
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - michaelaye
requirements:
  host:
  - pip
  - python
  - packaging
  - tomlkit
  - pandas
  - pvl
  - numpy
  - python-dateutil
  - tqdm
  - lxml
  - yarl
  - hirise-tools
  - kalasiris
  - dask
  - fastparquet
  run:
  - pip
  - python
  - packaging
  - tomlkit
  - pandas
  - pvl
  - numpy
  - python-dateutil
  - tqdm
  - lxml
  - yarl
  - hirise-tools
  - kalasiris
  - dask
  - fastparquet
test:
  imports:
  - planetarypy
