package:
  name: planetarypy
  version: 0.15.0
source:
  sha256: de1c2edaff710620c23651f268f78c4e95a43e61a470570187ea37b943bab2bf
  url: https://files.pythonhosted.org/packages/ef/5f/ab39a48cc7857d03ccc31a23692371d900221608b80a307efac011b6b397/planetarypy-0.15.0.tar.gz
about:
  dev_url: https://michaelaye.github.io
  doc_url: https://michaelaye.github.io
  home: https://michaelaye.github.io
  license: Apache Software
  license_family: APACHE
  summary: Python Tools for Planetary Science
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - michaelaye
requirements:
  host:
  - pip
  - python
  - packaging
  - tomlkit
  - pandas
  - pvl
  - numpy
  - python-dateutil
  - tqdm
  - lxml
  - yarl
  - hirise-tools
  - kalasiris
  - dask
  run:
  - pip
  - python
  - packaging
  - tomlkit
  - pandas
  - pvl
  - numpy
  - python-dateutil
  - tqdm
  - lxml
  - yarl
  - hirise-tools
  - kalasiris
  - dask
test:
  imports:
  - planetarypy
