package:
  name: planetarypy
  version: 0.16.0
source:
  sha256: bb7aca8f2f99d7721bd9c290b45b9bf950be5aa11372368d84386c1b56587f22
  url: https://files.pythonhosted.org/packages/ac/c1/4eca247ddbcf8b095e83c3fe59c05c23ad003eeb7685e74196ee22b1f1d8/planetarypy-0.16.0.tar.gz
about:
  dev_url: https://michaelaye.github.io
  doc_url: https://michaelaye.github.io
  home: https://michaelaye.github.io
  license: Apache Software
  license_family: APACHE
  summary: Python Tools for Planetary Science
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - michaelaye
requirements:
  host:
  - pip
  - python
  - packaging
  - tomlkit
  - pandas
  - pvl
  - numpy
  - python-dateutil
  - tqdm
  - lxml
  - yarl
  - hirise-tools
  - kalasiris
  - dask
  run:
  - pip
  - python
  - packaging
  - tomlkit
  - pandas
  - pvl
  - numpy
  - python-dateutil
  - tqdm
  - lxml
  - yarl
  - hirise-tools
  - kalasiris
  - dask
test:
  imports:
  - planetarypy
