package:
  name: planetarypy
  version: 0.21.3
source:
  sha256: 21aa160f8b192b61802f24e29f0d50aaa34c0f4a4e8911c790497fb60b6e5e77
  url: https://files.pythonhosted.org/packages/0d/27/09f9d7c7a072346a511ae828726b89473de17d289ebd7bda8077b4ca9256/planetarypy-0.21.3.tar.gz
about:
  dev_url: https://michaelaye.github.io
  doc_url: https://michaelaye.github.io
  home: https://michaelaye.github.io
  license: Apache Software
  license_family: APACHE
  summary: Python Tools for Planetary Science
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - michaelaye
requirements:
  host:
  - pip
  - python
  - packaging
  - tomlkit
  - pandas
  - pvl
  - numpy
  - python-dateutil
  - tqdm
  - lxml
  - yarl
  - kalasiris
  - dask
  - fastparquet
  - rioxarray
  - matplotlib
  - hvplot
  - requests
  - astropy
  - fastcore
  run:
  - pip
  - python
  - packaging
  - tomlkit
  - pandas
  - pvl
  - numpy
  - python-dateutil
  - tqdm
  - lxml
  - yarl
  - kalasiris
  - dask
  - fastparquet
  - rioxarray
  - matplotlib
  - hvplot
  - requests
  - astropy
  - fastcore
test:
  imports:
  - planetarypy
