package:
  name: planetarypy
  version: 0.15.1
source:
  sha256: 3f04fc4dd3030b0d4390d2b06195d11c45763a9086376eae7d24d27952247cbb
  url: https://files.pythonhosted.org/packages/9f/22/56d8159b600e9bddac96a686c1d7dfc3ddef4ef6d3e12a1841b2fa7ca3ed/planetarypy-0.15.1.tar.gz
about:
  dev_url: https://michaelaye.github.io
  doc_url: https://michaelaye.github.io
  home: https://michaelaye.github.io
  license: Apache Software
  license_family: APACHE
  summary: Python Tools for Planetary Science
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - michaelaye
requirements:
  host:
  - pip
  - python
  - packaging
  - tomlkit
  - pandas
  - pvl
  - numpy
  - python-dateutil
  - tqdm
  - lxml
  - yarl
  - hirise-tools
  - kalasiris
  - dask
  run:
  - pip
  - python
  - packaging
  - tomlkit
  - pandas
  - pvl
  - numpy
  - python-dateutil
  - tqdm
  - lxml
  - yarl
  - hirise-tools
  - kalasiris
  - dask
test:
  imports:
  - planetarypy
