name: Deploy to GitHub Pages
on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('etc/environment.yml') }}

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          python-version: "3.10"
          channels: conda-forge
          channel-priority: strict
          activate-environment: testenv
          environment-file: etc/environment.yml
          use-only-tar-bz2: true
          use-mamba: true

      - name: Install package
        run: |
          mamba install pip -y
          python gh_workflow_install_deps.py
          pip install -e ".[dev]"

      - name: Install tools and create docs
        run: |
          wget -nv https://www.quarto.org/download/latest/quarto-linux-amd64.deb
          sudo dpkg -i quarto*.deb
          echo "installed quarto"
          pip install -Uq git+https://github.com/fastai/fastcore.git
          pip install -Uq git+https://github.com/fastai/execnb.git
          pip install -Uq git+https://github.com/fastai/nbdev.git
          nbdev_docs

      - name: Install ghapi
        # this needs to be in the default shell so that below's default Python shell can activate GH pages
        shell: bash
        run: |
          pip install -Uq git+https://github.com/fastai/ghapi.git # you need this for enabling pages
          pip install -Uq git+https://github.com/fastai/nbdev.git

      - name: Enable GitHub Pages
        shell: python
        run: |
          import ghapi.core,nbdev.config,sys
          msg="Please enable GitHub Pages to publish from the root of the `gh-pages` branch per these instructions - https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch"
          try:
            api = ghapi.core.GhApi(owner=nbdev.config.get_config().user, repo=nbdev.config.get_config().repo, token="${{github.token}}")
            api.enable_pages(branch='gh-pages')
          except Exception as e: 
            print(f'::error title="Could not enable GitHub Pages Automatically":: {msg}\n{e}')
            sys.exit(1)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          force_orphan: true
          publish_dir: ./_docs
          # The following lines assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
