name: Deploy to GitHub Pages
on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          python-version: "3.10"
          channels: conda-forge
          channel-priority: strict
          activate-environment: testenv
          use-mamba: true
      # - name: Setup Conda
      #   # You may pin to the exact commit or the version.
      #   # uses: s-weigand/setup-conda@12b718b536e4be4da931f6d0fcfcc40a646ffed9
      #   uses: s-weigand/setup-conda@v1.1.1
      #   with:
      #     # Whether to activate the conda base env (Default: 'true')
      #     activate-conda: # optional, default is true
      #     # If conda should be updated before running other commands (Default: 'false')
      #     update-conda: # optional, default is false
      #     # Python version which should be installed with conda (default: 'Default')
      #     python-version: "3.10" # optional, default is default
      #     # Additional channels like 'conda-forge' which can be used to install packages
      #     conda-channels: "conda-forge" # optional, default is

      # - name: Install mamba
      #   shell: bash
      #   run: conda install -c conda-forge mamba -y

      - name: Install dependencies and package
        shell: bash -l {0}
        run: |
          # source ~/.profile
          # conda activate testenv
          mamba install pip -y
          python gh_workflow_install_deps.py
          pip install -e ".[dev]"
          pip install -Uq git+https://github.com/fastai/ghapi.git # you need this for enabling pages
          pip install -Uq git+https://github.com/fastai/fastcore.git
          pip install -Uq git+https://github.com/fastai/execnb.git
          pip install -Uq git+https://github.com/fastai/nbdev.git

      -name: Check it is working
        shell: bash -l {0}
        run: |
          echo $(which pip)
          mamba list gdal
          mamba list nbdev

      # - name: Install quarto
      #   shell: bash
      #   run: |
      #     wget -nv https://www.quarto.org/download/latest/quarto-linux-amd64.deb
      #     sudo dpkg -i quarto*.deb
      #     echo "installed quarto"

      # - name: Create docs
      #   shell: bash
      #   run: nbdev_docs
