name: Deploy to GitHub Pages
on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare nbdev doc creation
        uses: michaelaye/workflows/nbdev_prep@main
        with:
          pre: false
